dawnix/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views

urlpatterns = [
 path('', views.principal, name='principal'),
 path('usuarios', views.usuarios, name='usuarios'),
 path('peliculas', views.peliculas, name='peliculas'),
 path('usuarios/<int:pk>', views.usuario),
 path('usuarios/eliminar/<int:pk>', views.eliminarUsuario),
 path('peliculas/eliminar/<int:pk>', views.eliminarPelicula),
 path('peliculas/<int:pk>', views.pelicula),
 path('peliculas/buscar/<titulo>', views.busqueda),
 path('peliculas/<genero>', views.peliculasGenero),
 path('peliculas/favoritas/<usuario>', views.peliculasFavoritas),
 path('peliculas/favoritas/<usuario>/insertar/<int:pk>', views.insertarFavoritas),
 path('usuarios/edit', views.Usuario, name='editar'),

]

dawnix_dj/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import TemplateView, RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url='/dawnix/', permanent=True)),
    path('dawnix/', include('django.contrib.auth.urls')),
    path('dawnix/principal/', include('dawnix.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

dawnix/models.py
import uuid
from decimal import Decimal

from django.db import models
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import *
from django.contrib.auth.models import User
from rest_framework import serializers
from rest_framework.compat import MinValueValidator, MaxValueValidator


class Peliculas(models.Model):
    titulo = models.CharField(max_length=100, null=True)
    categorias = models.TextField(null=True, blank=True)
    descripcion = models.TextField(null=True, blank=True)
    año = models.DateField(null=True, blank=True)
    director = models.CharField(max_length=100, null=True, blank=True)
    reparto = models.TextField(null=True, blank=True)
    valoracion = models.DecimalField(max_digits=3, decimal_places=1,
                                     validators=[MinValueValidator(0), MaxValueValidator(10)], null=True, blank=True)
    URLVideo = models.URLField(null=True)
    URLPortada = models.URLField(null=True, blank=True)


    def __str__(self):
        return self.titulo


class Registro(UserCreationForm):
    first_name = forms.CharField(max_length=140, required=True)
    last_name = forms.CharField(max_length=140, required=False)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            'username',
            'email',
            'first_name',
            'last_name',
            'password1',
            'password2',
        )


class Usuario(serializers.ModelSerializer):
    class Meta:
        model = User
        fields = (
            'id',
            'first_name',
            'last_name',
            'email',
        )


class ModificarUsuarios(ModelForm):
    class Meta:
        model = User
        fields = (
            'first_name',
            'last_name',
            'email',
        )


class ModificarPelicula(ModelForm):
    class Meta:
        model = Peliculas
        fields = (
            'titulo',
            'URLVideo',

        )


class RegistroPelicula(ModelForm):
    class Meta:
        model = Peliculas
        fields = (
            'titulo',
            'categorias',
            'descripcion',
            'año',
            'director',
            'reparto',
            'valoracion',
            'URLPortada',
            'URLVideo',
        )


class Generos(models.Model):
    genero = models.CharField(max_length=200)
    peliculas = models.TextField(null=True, default='null')

    def __str__(self):
        return self.genero


class Favoritos(models.Model):
    usuario = models.CharField(max_length=100)
    favoritas = models.TextField(null=True, default='null')

    def __str__(self):
        return self.usuario

dawnix/views.py
# Create your views here.
from django.contrib.auth.forms import UserCreationForm
import requests
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.template import loader
from django.contrib.auth.models import User
from rest_framework.decorators import api_view

from dawnix.models import Registro, Usuario, Favoritos, Peliculas, RegistroPelicula, ModificarPelicula, Generos
from dawnix.models import ModificarUsuarios
from django.core.exceptions import ObjectDoesNotExist
from django.db.models import Q

def principal(request):
    """
    View function for home page of site.
    """
    # Render the HTML template index.html
    return render(
        request,
        'principal.html',
    )


def usuarios(request):

    if request.method == 'GET':
        usuario = User.objects.all()
        template = loader.get_template('administrar-usuarios.html')
        context = {
            'usuario': usuario,
            'form': Registro(),
            'form_m': ModificarUsuarios(),
        }
        return HttpResponse(template.render(context, request))

    elif request.method == 'POST':
        form = Registro(request.POST)

        if form.is_valid():
            fav = Favoritos()
            fav.usuario = form.data.get('username')
            fav.save()
            form.save()
            return HttpResponseRedirect('/dawnix/principal/usuarios')
        else:
            html = "<html><head><link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'>" \
                   "</head><body><div class='alert alert-danger m-5'>"+str(form.errors.as_data())+"</div></body></html>"
            return HttpResponse(html)


def peliculas(request):
    if request.method == 'GET':
        pelicula = Peliculas.objects.all()
        template = loader.get_template('administrar-peliculas.html')
        context = {
            'pelicula': pelicula,
            'form': RegistroPelicula(),
            'form_m': ModificarPelicula(),
        }
        return HttpResponse(template.render(context, request))

    elif request.method == 'POST':
        form = RegistroPelicula(request.POST)
        if form.is_valid():
            response = requests.get('https://api.themoviedb.org/3/search/movie?api_key=831e08f1af6a358dffb3e2b2790c7f3a&language=es-ES&query='+form.data.get('titulo')+'&page=1&include_adult=true');
            contenido = response.json()
            id = contenido['results'][0]['id']
            responsePelicula = requests.get('https://api.themoviedb.org/3/movie/'+str(id)+'?api_key=831e08f1af6a358dffb3e2b2790c7f3a&language=es-ES');
            busquedaRealizada = responsePelicula.json();

            # Video
            responseVideo = requests.get('https://api.themoviedb.org/3/movie/'+str(id)+'/videos?api_key=831e08f1af6a358dffb3e2b2790c7f3a&language=es-ES');
            video = responseVideo.json();

            # Reparto
            responseReparto = requests.get('https://api.themoviedb.org/3/movie/'+str(id)+'/credits?api_key=831e08f1af6a358dffb3e2b2790c7f3a');
            reparto = responseReparto.json();
            rep = ''
            todos = reparto['cast']
            for i in range(0, 5):
                if i != 4:
                    rep += todos[i]['name'] + ', '
                else:
                    rep += todos[i]['name']
            encontrarDirector = reparto['crew']
            j = 0
            while j < len(encontrarDirector[j]['job']) and encontrarDirector[j]['job'] != 'Director':
                j += 1

            # Categoria
            cate = ''
            numero = 0
            cantidad = len(busquedaRealizada['genres']) - 1

            catego = []

            for elemnt in busquedaRealizada['genres']:
                catego.append(elemnt['name'])
                if numero != cantidad:
                    cate += elemnt['name'] + ', '
                    numero += 1
                else:
                    cate += elemnt['name']

            obj = Peliculas()
            obj.titulo = busquedaRealizada['title']
            obj.URLVideo = 'https://www.youtube.com/embed/'+video['results'][0]['key']
            obj.valoracion = busquedaRealizada['vote_average']
            obj.año = busquedaRealizada['release_date']
            obj.categorias = cate
            obj.descripcion = busquedaRealizada['overview']
            obj.URLPortada = 'https://image.tmdb.org/t/p/original'+busquedaRealizada['poster_path']
            obj.director = encontrarDirector[j]['name']
            obj.reparto = rep

            obj.save()

            # Guardar genero
            for elemnt in catego:
                genero(elemnt, obj.id)

            return HttpResponseRedirect('/dawnix/principal/peliculas')
        else:
            html = "<html><head><link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'>" \
                   "</head><body><div class='alert alert-danger m-5'>"+str(form.errors.as_data())+"</div></body></html>"
            return HttpResponse(html)


def genero(genero, id):
    try:
        respestaGenero = Generos.objects.get(genero=genero)
        arrayPeliculas = respestaGenero.peliculas

        if arrayPeliculas == 'null':
            respestaGenero.peliculas = id
        else:
            respestaGenero.peliculas = respestaGenero.peliculas + ',' + str(id)
        respestaGenero.save()
        return

    except ObjectDoesNotExist:
        return


def peliculasGenero(request, genero):

    respuestaPeliculas = Generos.objects.get(genero=genero)
    peliculas = respuestaPeliculas.peliculas

    respuesta = {
        'peliculas': peliculas
    }
    return JsonResponse(respuesta, safe=False)


def usuario(request, pk):
    try:
        if request.method == 'GET':
            response = User.objects.get(id=pk)
            usuario = {
                'id': response.id,
                'username': response.username,
                'first_name': response.first_name,
                'last_name': response.last_name,
                'email': response.email,
            }
            return JsonResponse(usuario)

        elif request.method == 'POST':
            form_m = ModificarUsuarios(request.POST)

            if form_m.is_valid():
                obj = User.objects.get(id=pk)
                if form_m.cleaned_data['email'] != '':
                    obj.email = form_m.cleaned_data['email']
                if form_m.cleaned_data['first_name'] != '':
                    obj.first_name = form_m.cleaned_data['first_name']
                if form_m.cleaned_data['last_name'] != '':
                    obj.last_name = form_m.cleaned_data['last_name']
                obj.save()
                return HttpResponseRedirect('/dawnix/principal/usuarios')
            else:
                html = "<html><head><link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'>" \
                   "</head><body><div class='alert alert-danger m-5'>"+str(form_m.errors.as_data())+"</div></body></html>"
                return HttpResponse(html)

    except ObjectDoesNotExist:
        usuario = {
            'error': 'No existe el usuario'
        }

    return JsonResponse(usuario)


def pelicula(request, pk):
    try:
        if request.method == 'GET':
            response = Peliculas.objects.get(id=pk)
            pelicula = {
            'id': response.id,
            'titulo': response.titulo,
            'categorias': response.categorias,
            'descripcion': response.descripcion,
            'año': response.año,
            'director': response.director,
            'reparto': response.reparto,
            'valoracion': response.valoracion,
            'video': response.URLVideo,
            'portada': response.URLPortada,
            }
            return JsonResponse(pelicula)

        elif request.method == 'POST':
            form_m = ModificarPelicula(request.POST)

            if form_m.is_valid():
                obj = Peliculas.objects.get(id=pk)
                if form_m.cleaned_data['titulo'] != '':
                    obj.titulo = form_m.cleaned_data['titulo']
                if form_m.cleaned_data['URLVideo'] != '':
                    obj.URLVideo = form_m.cleaned_data['URLVideo']
                obj.save()
                return HttpResponseRedirect('/dawnix/principal/peliculas')
            else:
                html = "<html><head><link rel='stylesheet' href='https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css'>" \
                   "</head><body><div class='alert alert-danger m-5'>"+str(form_m.errors.as_data())+"</div></body></html>"
                return HttpResponse(html)

    except ObjectDoesNotExist:
        pelicula = {
            'error': 'No existe la película'
        }

    return JsonResponse(pelicula)


def eliminarUsuario(request, pk):
    usuario = User.objects.get(id=pk)
    favoritos = Favoritos.objects.get(usuario=usuario.username)
    favoritos.delete()
    usuario.delete()
    return HttpResponseRedirect('/dawnix/principal/usuarios')


def eliminarPelicula(request, pk):
    pelicula = Peliculas.objects.get(id=pk)

    # Eliminar pelicula de su categoria correspondiente
    generos = Generos.objects.all()
    for tabla in generos:
        if tabla.peliculas != 'null':
            idPelis = tabla.peliculas.split(',')
            idBuscar = str(pk)

            if idPelis.count(idBuscar) != 0:
                idPelis.remove(idBuscar)
                if len(idPelis) == 0:
                    tabla.peliculas = 'null'
                else:
                    numero = 0
                    cantidad = len(idPelis)-1
                    stro = ''
                    for elem in idPelis:
                        if numero != cantidad:
                            stro += elem + ','
                            numero += 1
                        else:

dawnix/templates/administrar-usuarios.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">

<head>
    <!-- Codificación -->
    <meta charset="utf-8">
    <!-- Compatibilidad IE-edge -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- Título -->
    <title>DAWNIX</title>
    <!-- Complementos necesarios -->
    <link rel="icon" type="image/png" href="{% static 'IMG/logorosa.png' %}" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" >
    <link rel="stylesheet" href="{% static 'CSS/principal.css' %}">
    <link rel="stylesheet" href="{% static 'CSS/administrador.css' %}">
</head>

<body class="text-white">

    {% block content %}
    {% if user.is_authenticated %}

        <div id="header" class="fixed-top">
            <!-- Barra de menú -->
            <nav class="navbar navbar-expand-md navbar-dark degradado pr-2">
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto align-items-center">
                        <li class="mr-2">
                            <img class="mr-2" src="{% static 'IMG/logoblanco.png' %}" height="50" width="50">
                        </li>
                        <li class="nav-item mr-2">
                            <a class="nav-link text-white" href="{% url 'principal' %}">Inicio</a>
                        </li>
                        {% if user.is_staff %}
                            <li class="nav-item mr-2">
                                <a class="nav-link text-white" href="{% url 'usuarios' %}">Administrar usuarios</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" href="{% url 'peliculas' %}">Administrar películas</a>
                            </li>
                        {%  endif  %}
                    </ul>
                    <!-- Barra de búsqueda -->
                    <div class="form-inline my-2 my-lg-0">
                        <input class="form-control mr-sm-2" type="text" id="contenido" name="contenido" placeholder="Título..." disabled>
                        <button class="btn btn-outline-light my-2 my-sm-0" id="busqueda" type="submit" disabled>Buscar</button>
                    </div>
                </div>

                <!-- Perfil de usuario -->
                <ul class="navbar-nav flex-row ml-4 mr-lg-0">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle  mr-lg-0 d-flex align-items-center" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><p class="m-1 text-capitalize">{{ user.username }}</p><i class="fa fa-user m-1"></i><span class="caret"></span>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right dropleft" aria-labelledby="navbarDropdownMenuLink">

                            <a class="dropdown-item" href="{% url 'logout' %}">Cerrar sesión</a>
                        </div>

                    </li>
                </ul>
                <button class="navbar-toggler ml-lg-0" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </nav>
        </div>

        <div id="busquedas" class="mt-6">

            <!-- Modal para añadir usuarios -->
            <div class="modal fade" id="modal-añadir-usuario" tabindex="-1" role="dialog" aria-labelledby="modalAñadirLabel" aria-hidden="true">
                <div class="modal-dialog" role="form">
                    <div class="modal-content">
                        <div class="modal-header degradado">
                            <h5 class="text-white" id="modalModificarLabel">Añadir usuario</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                        </div>
                        <div class="modal-body text-black">
                            {% block contento %}
                                    {% if form %}
                                        <form class="form-añadir"  method="post">
                                            {% csrf_token %}
                                            <input class="form-control mb-2 mt-2" name="username" id="id_username" type="text" placeholder="Usuario" required/>
                                            <input class="form-control mb-2 mt-2" name="email" id="id_email" type="email" placeholder="Correo" required/>
                                            <input class="form-control mb-2 mt-2" name="first_name" id="id_first_name" type="text" placeholder="Nombre" required/>
                                            <input class="form-control mb-2 mt-2" name="last_name" id="id_last_name" type="text" placeholder="Apellidos" required/>
                                            <input class="form-control mb-2 mt-2" name="password1" id="id_password1" type="password" placeholder="Contraseña" required/>
                                            <input class="form-control mb-2 mt-2" name="password2" id="id_password2" type="password" placeholder="Repita la Contraseña" required/>
                                            <input class="btn btn-block btn-outline-dark mb-2 mt-3" type="submit" value="Registrar usuario">

                                        </form>
                                    {% else %}
                                        <span class="text-dark">No activo</span>
                                    {% endif %}
                            {% endblock contento %}
                        </div>
                    </div>
                </div>
            </div>

            <!-- Modal para modificar los usuarios -->
            <div class="modal fade" id="modal-modificar-usuario" tabindex="-1" role="dialog" aria-labelledby="modalModificarLabel" aria-hidden="true">
                <div class="modal-dialog" role="form">
                    <div class="modal-content">
                        <div class="modal-header degradado">
                            <h5 class="text-white" id="modalModificarLabel">Modificar usuario</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                        </div>
                        <div class="modal-body">
                            {% block modify %}
                                    {% if form_m %}
                                        <form id="modaleditar" class="form-modificar" method="POST" action="">
                                            {% csrf_token %}
                                            <div id="editar"></div>
                                        </form>
                                    {% else %}
                                        <span class="text-dark">No activo</span>
                                    {% endif %}
                            {% endblock modify %}
                        </div>
                    </div>
                </div>
            </div>

            <!-- Modal para eliminar los usuarios -->
            <div class="modal fade" id="modal-eliminar-usuario" tabindex="-1" role="dialog" aria-labelledby="modalEliminarLabel" aria-hidden="true">
                <div class="modal-dialog" role="form">
                    <div class="modal-content">
                        <div class="modal-header degradado">
                            <h5 class="text-white" id="modalModificarLabel">Eliminar usuario</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        <div class="modal-body">
                            <h6 class="linea-eliminar">¿Desea eliminar al usuario?</h6>
                            <form id="botonEliminar" method='POST' action=''>
                                {% csrf_token %}
                                <div id="botones"> </div>
                            </form>

                        </div>
                    </div>
                </div>
            </div>

            <!-- Párrafo aclarativo -->
            <h6 class="linea-aclarativa d-flex justify-content-between align-items-center text-white">Seleccione el usuario que desea modificar:
                <button type="button" class="btn btn-outline-success" data-toggle="modal" data-target="#modal-añadir-usuario">
                    <span class="nuevo-usuario">Nuevo Usuario</span>
                </button>
            </h6>

            <!-- Barra de búsqueda -->
            <div class="input-group busqueda-admin">
                <input id="filtrar" type="text" class="form-control" placeholder="Introduce el nombre del usuario">
            </div>

            <!-- Lista de usuarios -->
            <div>
            <table class="table table-hover ">
                  <thead class="thead-dark">
                    <tr>
                      <th scope="col">#</th>
                      <th scope="col">Usuario</th>
                      <th scope="col">Nombre</th>
                      <th scope="col">Apellidos</th>
                      <th scope="col">Correo</th>
                      <th scope="col">Opciones</th>
                    </tr>
                  </thead>
                <tbody class="buscar" >
                    {% for user in usuario %}
                         <tr>
                            <th class="atributo-id">{{ user.id }}</th>
                            <td class="atributo-usuario" >{{ user.username }}</td>
                            <td class="atributo-nombre" >{{ user.first_name }}</td>
                            <td class="atributo-apellidos" >{{ user.last_name }}</td>
                            <td class="atributo-email">{{ user.email }}</td>
                            <td class="atributo-botones">
                                <button type="button" onclick="myFunction({{ user.id }})" class="btn btn-outline-dark" data-toggle="modal" data-target="#modal-modificar-usuario"><span class="lapiz"><i class="far fa-edit"></i></span></button>
                                <button type="button" onclick="paseUsuario({{ user.id }})" id="delete" class="btn btn-outline-danger" data-toggle="modal" data-target="#modal-eliminar-usuario"><span class="cruz"><i class="far fa-times-circle"></i></span></button>
                            </td>
                         </tr>
                    {% endfor %}
                </tbody>
            </table>
            </div>

        </div>


        <!-- Introducimos el footer en nuestra página -->
        <footer class="d-flex justify-content-center align-items-end text-white">
            <p class="mb-2"><small>&copy; Copyright 2019 dawnix.com</small></p>
        </footer>

        <!-- Script necesarios -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="https://code.jquery.com/jquery-1.12.4.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

        <script type="text/javascript" src="{% static 'JS/adminUsuarios.js' %}"></script>

    {% else %}
        <div class="h-100 d-flex flex-column justify-content-center align-items-center">
            <p>Debe iniciar sesión antes de poder acceder a la página</p>
            <a class="btn btn-outline-light my-2 my-sm-0" href="{% url 'login' %}">Iniciar sesión</a>
        </div>
    {% endif %}
    {% endblock %}
</body>

</html>